#!/bin/bash
#
# make-build-info.sh — write MiniproUI/BuildInfo.swift, the commit details the
# app shows on its info screen.
#
# MiniproUI is a synchronized folder group, so Xcode works out what to compile
# when it loads the project - before any build phase runs. BuildInfo.swift is
# git-ignored, so on a machine that has never built the project it does not
# exist at that moment, is left out of the target, and the build fails on the
# three missing functions no matter that a build phase writes it later. Run this
# once before the first xcodebuild; the build phase then keeps it current.
#
# The file is only rewritten when its contents change, so an unchanged commit
# does not force everything that uses it to recompile.
#
# Usage: Scripts/make-build-info.sh [--help]

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd -- "${SCRIPT_DIR}/.." && pwd)
OUTPUT="${PROJECT_ROOT}/MiniproUI/BuildInfo.swift"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    sed -n '3,17p' "${BASH_SOURCE[0]}" | sed 's|^# \{0,1\}||'
    exit 0
fi

# A source tarball has no git metadata; the info screen then says "unknown"
# rather than failing the build.
git_value() {
    git -C "$PROJECT_ROOT" "$@" 2>/dev/null || echo unknown
}

BRANCH=$(git_value rev-parse --abbrev-ref HEAD)
COMMIT=$(git_value rev-parse HEAD)
DATE=$(git_value show -s --format=%ci)

CONTENT=$(cat <<EOF
// Visual Minipro Build Commit Details

// Autogenerated - do not modify manually

func getGitBranch() -> String { "${BRANCH}" }
func getGitCommit() -> String { "${COMMIT}" }
func getCommitDate() -> String { "${DATE}" }
EOF
)

if [ ! -f "$OUTPUT" ] || [ "$(cat "$OUTPUT")" != "$CONTENT" ]; then
    printf '%s\n' "$CONTENT" > "$OUTPUT"
fi
